### ISSUE TITLE
duplicate records in issues.json

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/issue-tracker-archive#4]
@gschare : I noticed that the first 102 records in the issues.json repeat. That is, the sequence of records 1-102 appears twice consecutively before record 103.

**Comment by gschare** [comment]
Ah, that's probably from when I tested it with just the first 102. I will clear it and run it again.

**Comment by gschare** [comment]
Turns out it wasn't that I had ran it twice. It's that I was looping over the page numbers with `range(30)`, which by default starts at `0`, but GitHub page numbers in the REST API start at `1`, so I presume the `0` defaulted to the first page. Then when the loop happened, it took the first 102 issues for page number 0 (which became 1) and then did it again for page number 1.

Fixed by commit b532352.
